label chapter_3_2:
    play music "bgm/beat1.mp3"
    centered"9월 20일 토요일"
    cia"도련님~"
    cia"빨리 일어나세요~"
    stephan"으……"
    scene bg mansion_emptyroom with dissolve
    cia"좋은 아침 입니다~!"
    stephan"지금……{cps=2} {/cps}시간이……?"
    cia"현재 오전 9시 10분 입니다"
    show stephan yawn at left
    stephan"주말인데 좀더 자게 놔둬……"
    "나는 다시 자려고 이불을 덮었는데"
    play sound "se/search_bag.mp3"
    "시아가 내 이불을 잡아서 방 구석으로 멀리 던졌다"
    cia"그럼 아침 식사는 하시고 나서 다시 주무세요"
    stephan"쳇……"
    hide stephan yawn
    play sound "se/footsteps_wood.mp3"
    $ renpy.pause(3)
    scene bg test2 with dissolve # 주방 배경
    seb"좋은 아침 입니다"
    show stephan at left
    stephan"좋은 아침"
    stephan"할아버지도 안녕히 주무셨어요?"
    grandpa"어―"
    grandpa"근데 스테반"
    grandpa"혹시 냉장고에 있던 에너지 드링크 못봤니?"
    stephan"그거 제가 어제 마셨는데요?"
    hide stephan
    show effect1
    play sound "se/shock.ogg"
    cia"{size=40}할아버님!{/size}" with lshake
    cia"의사 선생님이 카페인 끊으시라고 하셨잖아요!"
    hide effect1
    cia"저 몰래 또 마시고 계셨어요?!"
    grandpa"그,{cps=2} {/cps}그건……"
    show stephan shock at left
    stephan_think"역시 내 생각대로 였군……"
    hide stephan shock
    cia"참나,{cps=2} {/cps}제가 버려도, 버려도 끝도 없이 가지고 오신다니까……"
    seb"시아도 너무 그러지 마세요……"
    seb"할아버님께서도 그만큼 그 금고의 비밀번호를 풀고 싶으셨을 테니까요……"
    cia"아무리 그래도!{cps=2} {/cps}건강을 헤쳐가면서 까지 그러는 건 안돼요!"
    seb"하긴……{cps=2} {/cps}할아버님도 다음부턴 남들이 걱정할만한 행동은 하지 말아주세요……"
    grandpa"넌 누구편인게야!"
    "우리 넷은 가족같은 분위기 속에서 아침밥을 먹었다."
    scene bg lib_day with slideawayright
    "나는 식사를 마친 후 바로 도서실로 향했다."
    "그리고 다음 일기장을 바로 읽기로 했다."
    ################################1960년 3월 12일 일기장 시작############################
    scene black with memory
    nvl clear
    play music "bgm/smooth4.mp3"
    narrator_nvl"1960년 3월 12일 토요일"
    narrator_nvl"에드워드 토머 27세"
    narrator_nvl"날씨 - 조금 따뜻해짐"
    nvl clear
    narrator_nvl"내일 나랑 메리는 결혼식을 올린다."
    narrator_nvl"이유는 모르겠지만 메리가 가능하면 하객들을 초대 하지 않고 주례만 불러서 조용하게 결혼을 하자고 했다."
    narrator_nvl"난 메리만 좋다면 다 좋기 때문에 딱히 상관없다."
    narrator_nvl"어차피 난 혼인 신고만 하면 끝이니까……"
    scene bg ravine_day with dissolve # 절벽 풍경
    play bgs"bgs/birds.mp3"
    show mary
    mary"내일……{cps=2} {/cps}우리 여기서 결혼 하는거지?"
    edward"응……"
    mary"뭔가 실감이 안나……"
    mary"이름도 \'메리 슈테른\'에서 \'메리 토머\'가 된다니……"
    mary"결혼 하기 싫다는 뜻은 아니고!"
    mary"그냥……{cps=2} {/cps}꿈만 같다 랄까……?"
    edward"나도……"
    edward"이렇게 쉽게 될줄 몰랐어……"
    mary"뭐가?{cps=2} {/cps}결혼?"
    edward"어,{cps=2} {/cps}응……"
    mary"혹시 에드워드는 기억나?!"
    mary"우리가 여기서 처음 만났던거!"
    edward"그땐 내가 완전히 좌절해서 술이나 계속 퍼마시고 있었지……"
    edward"그런데 네가 내 앞에 나타나서……"
    play sound "se/think.mp3"
    scene bg ravine_night with memory # 절벽 풍경 밤
    play bgs"bgs/night.mp3"
    someone"그 양복"
    extend" 아직 반납하기엔 이릅니다."
    play sound "se/think.mp3"
    scene bg ravine_day with memory # 절벽 풍경
    play bgs"bgs/birds.mp3"
    edward_think"그때 메리는……{cps=2} {/cps}나한테 있어서 여신과도 같았지……"
    edward_think"그런데 난 그런 메리를 이용하려고……"
    edward_think"아니야!{cps=2} {/cps}여기서 약해지면 안돼!"
    show mary
    mary"그거 보다 훨씬 전에 기억나?"
    edward"훨씬 전?"
    mary"우리가 처음 만났을때……"
    edward"그때가 그때 잖아"
    mary"아니……{cps=2} {/cps}그러니까 {size=40}훨~씬{/size} 전에!"
    edward"글쎄……"
    mary"뭐,{cps=2} {/cps}어쩔 수 없나……"
    mary"그래도 괜찮아!"
    mary"난 에드워드를 사랑하는 걸!"
    edward"나도……{cps=2} {/cps}사랑해……"
    "그때 내가 말한 \'사랑해\'는"
    "아마 진심 이었을거다……"
    stop bgs
    stop music
    scene black with dissolve
    centered"다음날"
    centered"결혼식 당일"
    play music "bgm/marriage.mp3"
    scene bg test with squares# 결혼식 일러스트
    "나랑 메리는 결혼식을 올렸다."
    "인원수도 메리가 말한대로 최소한으로 했고……"
    "장소도 우리 둘에게 있어서 소중한 장소로……"
    $ renpy.pause(3)
    scene bg test2 with dissolve # 결혼식 배경
    $ extra_name = '메리의 아버님'
    extra"메리……{cps=2} {/cps}정말 축하한다……"
    show mary at left
    $ renpy.vibrate(0.3)
    mary"콜록{cps=2} {/cps}콜록"
    mary"에이~{cps=2} {/cps}아빠도 참……"
    mary"그렇게 까지 울건 없잖아"
    extra"누,{cps=2} {/cps}누가 울었다고!"
    extra"그냥 눈에 먼지가……"
    edward"아버님……{cps=2} {/cps}정말 감사합니다!"
    extra"감사인사는 자네가 아니라 내가 해야 돼……"
    extra"정말 고마워……"
    extra"우리 메리 곁에 있어줘서……"
    edward"아니에요……{cps=2} {/cps}메리가 제 곁에 있어준겁니다."
    "내 눈에도 눈물이 조금씩 고였다."
    "왜 일까?"
    "어쩌면 내가 진심으로 메리를 사랑하고 있어서?"
    "아니면 내 양심에 가책을 느끼고 있어서……?"
    "어느쪽이든……"
    "이젠 상관없었다."
    extra"근데 신혼 여행은 어딜 갈 생각인가?"
    edward"그러고 보니까……{cps=2} {/cps}우리가 그걸 정하지 못했네"
    edward"메리의 몸 상태도 있으니까 어디 멀리 가진 못할테고……"
    mary"난 에드워드 옆이라면 어디든지 좋아!"
    mary"…………"
    mary"방금 한 말 너무 오글거렸어!"
    mary"못들은걸로 해줘!"
    edward"하하하하"
    edward"그건 나도 마찬가지야!"
    edward"메리랑 함께라면 어디든지 좋아!"
    scene black with dissolve
    nvl clear
    narrator_nvl"나랑 메리는 아버님이 사주신 별장에서 지내기로 했다."
    narrator_nvl"혼인 신고서도 식이 끝나고 나서 바로 작성 했으니……"
    narrator_nvl"이제 남은건 메리가 죽는날 까지 기다리는거 뿐……"
    stop music
    narrator_nvl"제발 빨리 죽었으면 좋겠다."
    narrator_nvl"안 그러면 내 마음이 버티질 못할거 같다."
    narrator_nvl"어쩌면 메리를 진심으로 사랑해 버릴지도 모른다……"
    nvl clear
    play music "bgm/beat5.mp3"
    narrator_nvl"1960년 3월 13일 일요일"
    narrator_nvl"에드워드 토머 27세"
    narrator_nvl"날씨 - 찬 바람이 살짝 붐"
    nvl clear
    narrator_nvl"벌써 봄이 찾아왔다."
    narrator_nvl"밖은 여전히 춥지만 그래도 꽃이 피기 시작했다."
    narrator_nvl"또, 결혼식이 끝난 뒤 우린 신혼집 에서 잠을 잤다."
    narrator_nvl"매일 매일 같이 자고 같이 일어나고……"
    narrator_nvl"나랑 메리는 이제 완전한 부부가 되었다."
    narrator_nvl"메리 때문에 내 가슴이 점점 괴로워 졌다."
    centered"오전 9시"
    scene bg test2 with moveright # 별장 침실 배경
    show mary
    $ mary_name = '메리 토머'
    mary"여보"
    mary"좋은 아침!"
    edward"벌써부터 여보라고 부르는거야……?"
    mary"벌써라니!"
    mary"원래 결혼 하자 마자 바로 여보라고 부르는거야!"
    edward"그,{cps=2} {/cps}그래……?"
    mary"한번 자기도 날 \'여보\'라고 불러봐"
    edward"으……"
    edward"오늘 아침은 뭘 까나~?"
    mary"말 돌리지 말고 빨리"
    show mary zoomin
    mary"여~보"
    mary"라고 말해"
    edward"{size=20}여……{cps=2} {/cps}보……{/size}"
    mary"더 크게"
    edward"{size=30}여……{cps=2} {/cps}보……{/size}"
    mary"똑바로!{cps=2} {/cps}더 크게!"
    edward"여보!"
    mary"왜요?{cps=2} {/cps}여보♡"
    edward"으아아아{cps=2} {/cps}오글거려!"
    mary"나는 뭐 안 오글 거리는줄 아나……"
    edward"그럼 안하면 되잖아!"
    mary"하지만……"
    mary"그럼 결혼 분위기가 안나잖아"
    edward"…………"
    mary"내가 살아 있는 동안은 결혼 분위기를 만끽 하고 싶은걸!"
    edward_think"이거 참……"
    edward"그래 알았어!"
    edward"여보,{cps=2} {/cps}나 배고파"
    edward"……이렇게 하면 되는 건가?"
    mary"응!"
    mary"금방 밥 차려줄게~{cps=2} {/cps}여보♡"
    edward_think"제발 끝에있는 그 하트 만이라도 어떻게;;"
    edward"근데 자기는 언제부터 회사에 출근 할거야?"
    mary"글쎄……"
    mary"그래도 몸이 예전보다 많이 괜찮아진거 같으니까 곧 갈 수 있을지도 몰라!"
    edward_think"몸이 괜찮아졌다고……?"
    mary"맞다!"
    mary"나 하고싶은 게 생겼어!"
    edward"뭔데?"
    mary"우리가 결혼식을 올린 그 절벽쪽 있잖아"
    mary"거기에 큰 저택을 한번 지어보고 싶어!"
    edward"저택?"
    mary"응"
    mary"어렸을때 부터 꿈이었거든!"
    edward_think"저택이라……"
    edward"저택 하면 거대하고, 부르주아 들이 살고 있는 그런 저택?"
    mary"맞아"
    edward_think"확실히 그런곳에 살 수 있다면 정말 멋있긴 하겠다……"
    edward"근데 왜 하필이면 저택이야?"
    mary"원랜 성을 짓고 싶었는데 그건 너무 비싸서 힘들거 같더라고"
    edward_think"아니, 가격이 문제가 아닌거 같은데;;"
    mary"아빠가 아는 건설 회사가 있는데 거기에 맡기면 분명 멋있는 저택을 지어줄지도 몰라!"
    mary"노스탤지어 토이즈 본사의 직원 휴개실 리모델링도 그 건설업체가 맡았거든"
    edward"직원 휴개실의 디자인이 멋있긴 했지……"
    mary"그래서 저택 하나 장만 할거?"
    edward"그래……"
    edward"메리만 괜찮다면 난 뭐든지 좋아"
    edward"근데 오늘은 일요일인데 영업을 하려나?"
    mary"아빠를 통해서 연락을 하면 적어도 예약은 할수 있을거야"
    edward"알았어"
    scene black with dissolve
    nvl clear
    narrator_nvl"그 이후로 우린 같이 살게 될 저택의 구조를 간단하게 설계했다."
    narrator_nvl"나중엔 건설 업체의 전문가와 상담을 해서 우리가 만든 설계도를 좀더 구체화 했고"
    narrator_nvl"드디어 저택의 건설이 확정되었다."
    narrator_nvl"그런데 집을 새로 짓는데 절차가 정말 복잡했다."
    narrator_nvl"이래서 다들 집을 새로 짓는것보단 이사를 추구하는가 보다……"
    nvl clear
    play music "bgm/happy2.mp3"
    narrator_nvl"1960년 3월 20일 일요일"
    narrator_nvl"에드워드 토머 27세"
    narrator_nvl"날씨 - 화창 함"
    nvl clear
    narrator_nvl"저택의 건설 장소는 우리가 처음 만났던 절벽쪽이다."
    narrator_nvl"물론 구조상 정확히 그 곳에선 짓기 힘들고, 그 주변이다."
    narrator_nvl"집을 짓는데 필요한 절차가 조금 복잡해서 건설 시작일이 1주일 정도 미뤄졌지만"
    narrator_nvl"그래도 메리가 살아있는 동안 건설이 시작되어서 정말 다행이다."
    narrator_nvl"덕분에 난 메리의 기쁜 모습을 볼수가 있었다."
    narrator_nvl"하지만 완공일이 조금 애매하다……"
    narrator_nvl"그때까지 메리가 건강 할 수 있을지……"
    narrator_nvl"나는 조금 걱정이 됐다."
    narrator_nvl"하지만 그덕분에 새로운 목표가 생겼다."
    narrator_nvl"그것은 메리의 소원을 하나하나 다 이뤄내는 것이다."
    narrator_nvl"메리가 죽기전에……{cps=2} {/cps}모든 소원을 이뤄주고 싶다."
    narrator_nvl"그리고 언제 부턴가 돈은 내 안중에도 없었다."
    scene bg test with dissolve # 저택 건설 뼈대를 에드랑 메리가 지켜보고 있는 일러(구도는 에드, 메리의 등 뒤로)
    play bgs "bgs/birds.mp3"
    mary"집은 이렇게 짓는거구나……"
    edward"처음봐?"
    mary"응"
    mary"난 항상 실내에만 있었으니까……"
    edward"훗……{cps=2} {/cps}난 예전에 저런일을 많이 해봐서 아주 잘 아는데!"
    edward"궁금한게 있으면 뭐든지 물어봐!"
    mary"정말?!"
    mary"그럼 저기있는 저 기구는 어디에 쓰는거야?"
    edward"저건 말이지……"
    edward_think"내가 만약 메리를 만나지 못했다면……"
    edward_think"아마 지금쯤 내가 저기서 공사하면서 지냈겠지?"
    edward_think"그리고 메리는……{cps=2} {/cps}예전에 말한 그 사람이랑 같이 있었을지도 모르고……"
    mary"에드워드!"
    edward"응?"
    stop music
    mary"저택은 언제 완공된데?"
    edward"그게……"
    "저택의 완공일……"
    stop bgs
    scene black with memory
    centered"저번주"
    $ extra_name = '건설 업체 직원'
    extra"이렇게 하면 다음주 쯤에 공사가 시작될듯 하네요."
    edward"다음주요……?"
    extra"네, 그때 쯤이면 주소 등록 이라든가, 각종 서류가 완성될테니까요."
    edward"참 복잡하네……"
    edward"그럼 그때 시작을 한다면, 완공일은 어떻게 되죠?"
    extra"음……"
    extra"날씨 등의 변수만 없다면 적어도 1년은 걸릴듯 싶습니다."
    edward"1년이요?!"
    play bgs "bgs/birds.mp3"
    scene bg test with memory # 저택 건설 뼈대를 에드랑 메리가 지켜보고 있는 일러(구도는 에드, 메리의 등 뒤로)
    "메리에게 어떻게 말을 해야 하는가……"
    "과연 메리가 저택이 완성되는 모습을 볼수있을지 정말 걱정이 되었다."
    "하지만 이건 어떻게 숨길수도 없는거고……"
    edward"저택의 규모가 조금 있다 보니까……"
    edward"1년 정도 걸릴거 같다네……"
    mary"그래?"
    mary"흠……{cps=2} {/cps}1년이란 말이지?"
    "메리의 반응은 조금 예상외였다."
    "난 메리가 생전에 완공된걸 못볼거라 생각하고 우울해 할 줄 알았는데"
    "의외로 괜찮았다."
    mary"자기 왜 그래?"
    edward"음, 어……?"
    edward"뭐,{cps=2} {/cps}뭐가?"
    mary"뭔가 기분이 다운 됐잖아!"
    mary"설마 내가 완공일까지 살아있지 못할거라 생각 하거나 그런건 아니겠지?!"
    edward"그,{cps=2} {/cps}그건……"
    edward"솔직히 조금 걱정이야"
    edward"저번에 의사 선생님이 말씀했잖아"
    edward"앞으로 1년 밖에 남지 않았다고……"
    mary"자기는 혹시 눈치체지 못했어?"
    edward"뭐가……?"
    mary"나 최근들어서 기침을 하는 획수가 현저히 줄었잖아!"
    edward"응?"
    edward"그러고 보니까 확실히……"
    mary"분명 에드워드가 내 옆에서 있어주니까 그런걸 거야!"
    mary"자기 옆에 있으면 너무 행복해서 숨이 빨리 쉬어지거든"
    mary"어쩌면 그거 때문에 폐에 있던 암세포도 조금 잠잠해진 걸 지도?"
    edward"글쎄……{cps=2} {/cps}그런 원리로 움직이는 게 아니라서……"
    mary"에이~{cps=2} {/cps}참 낭만이 없어요!"
    mary"하지만 병이라는 게 마음가짐 에서부터 온다는 말이 있잖아"
    mary"난 조금이라도 더 자기랑 오랜시간을 보내고싶어……"
    edward"그래도……{cps=2} {/cps}자기가 아프지 않다고 하니까 조금 안심이야"
    edward"자기가 아픈 모습은 정말 보기 싫거든……"
    mary"나도 그래"
    edward"그래도 병원엔 꼭 가보자"
    edward"전문의의 진단이 있어야 더 안심이 되니까"
    mary"응……."
    scene black with dissolve
    stop bgs
    play music "bgm/smooth2.mp3"
    nvl clear
    narrator_nvl"1960년 3월 21일 월요일"
    narrator_nvl"에드워드 토머 27세"
    narrator_nvl"날씨 - 구름이 낌"
    nvl clear
    narrator_nvl"오늘은 메리랑 같이 병원에 가봤다."
    narrator_nvl"메리는 자신의 몸상태가 괜찮다고 했지만"
    narrator_nvl"난 의사의 진단이 있어야 믿을수가 있었다."
    narrator_nvl"괜히 잘못해서 메리가 죽기라도 하면……"
    narrator_nvl"내가 어떻게 혼자서 살아가냐고……"
    scene bg diary_hospital_hall with slideawayright
    $ extra_name = '간호사'
    extra"메리 토머 환자님,{cps=2} {/cps}안으로 들어오세요!"
    play sound "se/footsteps_concrete.mp3"
    $ renpy.pause(3)
    play sound "se/door_open.ogg"
    scene bg diary_hospital_med with blinds
    $ extra_name = '의사'
    extra"메리 토머 씨 인가요……?"
    show mary
    mary"네"
    extra"먼저 간단한 검사를 위해서 따라와주세요."
    play sound "se/move.mp3"
    scene black with moveleft
    centered"검사 후"
    play sound "se/move.mp3"
    scene bg diary_hospital_med with moveleft
    edward"검사 결과가 어떤가요?"
    extra"일단 여기를 보시면……"
    "의사 선생님은 말해줘도 내가 알아 듣지 못하는 말을 반복했다."
    "하지만 목소리 톤으로 미루어 짐작 했을때 나쁜소식은 없는듯하다."
    edward"그래서 결과적으로 메리는 어떤거죠?"
    play music "bgm/smooth4.mp3"
    extra"축하드립니다.{cps=2} {/cps}몸 상태가 많이 개선됐어요."
    extra"저희 쪽에있는 의료기구만 가지곤 검사할 수 있는 게 한정되어 있지만"
    extra"그래도 눈에 뛸 정도로 상태가 많이 호전되었습니다."
    edward"정말인가요?!"
    extra"그래도 완치 된건 아니니까 너무 무리는 하지마세요."
    extra"잘못 했다간 다시 병이 재발 할지도 모르니까요."
    edward_think"메리의 상태가 괜찮아졌다고?"
    edward_think"그렇게 되면……"
    "그때 내 마음속에서 부터 울컥하는 감정이 쏟아져 나왔다."
    "돈을 벌지 못해 슬퍼서?{cps=2} {/cps}아니면 메리가 죽지 않아 기뻐서?"
    "둘다 아니다……"
    "정확한 이유는 내가 무슨짓을 하고있었는지 깨달아서다."
    "나를 진정으로 사랑해주는 여자를……{cps=2} {/cps}세상에 있을 날이 얼마 남지 않은 여자를……"
    "나는 돈을 벌기위한 수단으로써 사용하고 있었다."
    "그런 내 자신이 너무나도 싫고, 원망 스럽고, 부끄러웠다."
    "하지만 이젠……"
    edward"여보, 축하해"
    show mary
    mary"내가 말했잖아!{cps=2} {/cps}난 괜찮다고!"
    hide mary
    extra"다시 말하지만 완치된게 아니라는 걸 명심하세요!"
    edward"네!"
    edward"그럼 안녕히계세요"
    scene black with dissolve
    "하지만 이젠 달랐다."
    "내가 지금까지 지은 죄를 만회할 기회가 생겼다."
    "메리가 정말로 죽기전에 하고싶은 일을 전부 이뤄줄 수 있게 되었다."
    "그것도 거짓된 마음이 아닌 나의 진실된 마음으로"
    edward"여보"
    mary"응?"
    edward"사랑해"
    mary"오글거리게 왜그래……"
    edward"그냥……{cps=2} {/cps}다행이다 싶어서"
    nvl clear
    narrator_nvl"그 이후로 우린 꽤나 오랜 시간을 같이 보냈다."
    narrator_nvl"메리가 건강해 있는 동안……"
    narrator_nvl"난 최대한 많은것이 해주고 싶어졌다."
    narrator_nvl"예전에도 사뭇 비슷한 생각이 들긴 했지만……{cps=2} {/cps}역시 난 메리를 사랑하는가보다."
    play music "bgm/beat1.mp3"
    nvl clear
    narrator_nvl"1960년 3월 22일 화요일"
    narrator_nvl"에드워드 토머 27세"
    narrator_nvl"날씨 - 바람이 조금 붐"
    scene bg test2 with moveright # 별장 침실 배경
    edward"나 회사 다녀올게"
    mary"잠깐만!"
    show mary with dissolve
    edward"어?"
    edward"그 차림은?"
    mary"나도 오늘은 출근 할래!"
    edward"괜찮겠어?"
    mary"내가 한동안 출근을 하지 못해서 회사 상태가 말이 아닐거 아니야?"
    mary"빨리 가서 정리를 해야지!"
    edward"그래……"
    scene black with dissolve
    play music "bgm/sad4.mp3"
    nvl clear
    narrator_nvl"1960년 12월 18일 일요일"
    narrator_nvl"에드워드 토머 28세"
    narrator_nvl"날씨 - 눈이 많이 옴"
    nvl clear
    narrator_nvl"시한부 선거 받은 날로부터 벌써 1년이 지났는데도 메리는 건강하다."
    narrator_nvl"하지만 기침을 아예 안하는 건 아니다."
    narrator_nvl"그저 그 횟수, 강도가 많이 약해졌을 뿐이다."
    narrator_nvl"그래도 이 페이스라면 완치 될것만 같은 생각이 들었다."
    narrator_nvl"그 외에 또다른 좋은소식이 있다."
    narrator_nvl"저택의 완공일이 몇달 안남았다."
    narrator_nvl"메리는 건강하고……{cps=2} {/cps}저택도 완성될듯 해 보이고……"
    scene bg test2 with dissolve # 눈이 덮힌 저택 공사터
    show snow
    "오늘은 공휴일 이다."
    "그때문에 나랑 메리는 하루종일 집에만 있게 됐는데……"
    "메리가 집에만 있는것은 답답하다며 이쪽으로 산책을 가자고 했다."
    "솔직히 난 그냥 따뜻한 집에서 메리를 품속에 안고 하루종일 잠만 자고싶었는데……"
    "내 꿈이 너무 컸나보다……"
    show mary
    mary"저기! 눈 덮힌거 봐바!"
    edward"참 많이도 왔네……"
    mary"우리 눈싸움 하자!"
    edward"눈 싸움?"
    edward"괜찮겠어?"
    mary"설마 나한테 질거 같아서 겁이 난건가?"
    "그래도 이렇게 건강한 메리의 모습을 보는것도 나쁘진 않다."
    edward"후후……{cps=2} {/cps}그럴리가"
    edward"내가 힘이 좀 쎄니까 조심하는 게 좋을거……"
    hide mary
    play sound "se/fall.ogg"
    $ renpy.vibrate(0.4)
    show ev snowfight_hit with lshake
    edward"아야"
    edward"갑자기 뭐야……"
    hide ev snowfight_hit
    show mary
    mary"이기기 힘들거 같은 상대에겐 선빵이 최고지!"
    edward"아직 승부가 끝난건 아니다!!"
    hide mary with dissolve
    play sound "se/footsteps_running_snow.mp3"
    "나랑 메리는 한동안 눈을 던지면서 주변을 돌아다녔다."
    "얼마 전까지만 해도 암 환자였다는 게 정말 믿기지 않을 정도로 메리는 건강했다."
    scene black with moveleft
    centered"수 십분후"
    scene bg test2 with moveleft # 저택 공사 눈
    show snow
    show mary
    edward"후아……{cps=2} {/cps}힘들다……"
    mary"내가 이겼다!"
    edward"그래……{cps=2} {/cps}그래……"
    mary"오늘은 뭔가 신끼가 느껴지는군!"
    mary"연승의 느낌이야!{cps=2} {/cps}눈싸움 한판 더!"
    edward"네가 무슨 화투치는 아저씨냐;;"
    edward"그보다 난 지쳐서 더이상 못할거같아……"
    mary"참나……{cps=2} {/cps}자기는 힘 쎄다면서"
    edward"한동안 운동은 안하고 계속 책상에 앉아만 있어서 그런가봐……"
    mary"그럼 눈사람을 만드는 건 어때?"
    edward"뭐……{cps=2} {/cps}눈사람 정도면 괜찮을거 같네"
    mary"좋았어!"
    mary"세상에서 가장 큰 눈사람을 만들어보자고!"
    edward"왜 눈사람 까지도 힘들게 만들려는거야;;"
    "메리는 그대로 꿇어서 손으로 작은 눈 뭉치를 만들었다."
    "그리고 그 눈 뭉치를 굴려서 눈사람의 몸이 될 눈덩이를 만들고 있었다."
    "그런데 쟨 도대체 어디서 저런 채력이 나오는지 모르겠다……"
    "혹시 눈을 좋아하는 걸까?"
    edward"메리는 눈을 좋아해?"
    mary"어?"
    mary"뭐야 그 후진 작업멘트 같은건"
    edward"뭐,{cps=2} {/cps}뭐라고?!"
    mary"미안~ 미안~"
    mary"자기를 만나기 아주 오래 전에 어떤 남자가 비슷한 멘트를 한적이 있었거든"
    edward"나,{cps=2} {/cps}남자가?!"
    mary"대학교 시절땐 남자들이 어찌나 많이 대쉬를 하던지……"
    mary"진짜 별에 별 작업멘트가 있더라고"
    mary"그리고 자기가 말한대로 난 눈을 엄청 좋아해!"
    edward"역시나……{cps=2} {/cps}그렇지 않고서야 이렇게 힘을 낼리가 없지"
    mary"이유는 묻지 않는거야?"
    edward"물어봐줬으면 좋겠어?"
    mary"그런건 아니고……"
    edward"어,{cps=2} {/cps}음……"
    edward"자기는 눈을 왜 좋아해?"
    mary"그건 말이지……"
    mary"예전에 첫눈이 내리는 날에 고백을 하면 성공한다는 말이 있었잖아……"
    mary"그 말이 없었더라면 난 아마 에드워드한테 용기 내어서 고백을 하지 못했을거야"
    edward_think"메리……"
    play sound "se/search_bag.mp3"
    scene ev sky_snow with movedown
    edward"그렇게 생각하니까 나도 갑자기 눈이 좋아지네"
    mary"왜?"
    edward"하늘에서 떨어지는 눈을 보면 자기가 떠올라……"
    edward"그리고 난 자기가 좋아……{cps=2} {/cps}고로, 눈을 좋아하는거지……"
    stop music
    mary"…………"
    scene bg test2 with moveup # 저택 공사 눈
    edward_think"뭐야 이 침묵은?!"
    edward_think"뭐,{cps=2} {/cps}뭐라도 말을 좀 해줘바!"
    edward_think"갑자기 쪽팔리기 시작하잖아!"
    play music "bgm/sad4.mp3"
    mary"누,{cps=2} {/cps}눈사람이나 만들자!"
    edward"어,{cps=2} {/cps}어―!"
    hide mary with dissolve
    "나는 빠른 동작으로 눈덩이를 굴려서 크기를 키웠다."
    "그리고 얼마 지나지 않아서 눈사람이 완성되어갔다."
    scene bg test with slideleft # 눈사람 2개를 만든 일러스트
    show snow
    "완성된 눈사람은 마치 우리 둘을 연상시키듯이 나란이 세워 놓았고, 우린 같이 둘이서 완성한 작품을 바라봤다."
    mary"드디어 완성했다!"
    mary"작품명은 \'추억\'이라고 하겠어!"
    edward_think"\'추억\'……"
    "추억이라는 말이 내 가슴속을 울렸다……"
    show effect2
    play sound "se/shock2.mp3"
    edward"눈사람도 시간이 지나면 녹듯이, 추억도 시간이 지나면 잊혀져서 그런건가……"
    "그다지 추억이 없는 내 마음속을 울려버렸다……"
    hide effect2
    mary"헉!{cps=2} {/cps}왜 그렇게 부정적이야?"
    edward"그냥 옛날 생각이 나서……"
    edward"아니면, 옛날 생각이 안 나서 라고 표현을 하는 게 더 맞으려나……"
    mary"역시 기억이 없구나……"
    edward"내가 예전에 너한테 말한적이 있지 않나?"
    edward"난 어렸을때 바쁘게 살아서 딱히 기억에 남을만한 일이 없었다고……"
    mary"그런게 아니라……{cps=2} {/cps}내가 아까\'작품명은 추억이라고 하겠어!\' 했던거……"
    edward"어?"
    mary"내가 예전에 비슷한 말을 한적이 있었는데"
    edward"그랬었던가?"
    mary"뭔가 좀 쓸쓸하네……"
    edward_think"내가 뭘 잘못했나?!"
    scene black with dissolve
    nvl clear
    play music "bgm/happy1.mp3"
    narrator_nvl"1961년 4월 2일 일요일"
    narrator_nvl"에드워드 토머 28세"
    narrator_nvl"날씨 - 상쾌 함"
    nvl clear
    narrator_nvl"오늘 저택이 완성 되었다."
    narrator_nvl"최근 건설 제도가 바뀌면서 예상했던 완공일과는 많이 늦춰 졌지만 난 신경 쓰지 않는다."
    narrator_nvl"중요한건 메리가 건강한 모습으로 완성된 저택을 보았기 때문이다."
    narrator_nvl"저택에 필요한 가구의 배치도 전부 끝났고, 가스, 전기도 전부 사용이 가능하다."
    narrator_nvl"남은건 기존 집에 있는 물건들을 이쪽으로 옮기는거 뿐이다."
    scene bg grandpa_mansion with dissolve
    play bgs"bgs/birds.mp3"
    show mary
    mary"정말 멋있는 저택이네"
    edward"그러게……"
    mary"주변에 새소리도 정말 아름답고!"
    edward"……근데 집이 둘만 살기엔 좀 많이 크지 않나?"
    mary"그래도……{cps=2} {/cps}시간이 지나다 보면 가족 인원도 늘어나면서……{cps=2} {/cps}북적북적 해지겠지……"
    edward"응?"
    mary"아,{cps=2} {/cps}아무것도 아니야!"
    edward"어……"
    mary"그,{cps=2} {/cps}그보다 빨리 안에 들어가보자!"
    stop bgs
    play sound "se/door_open.ogg"
    scene bg diary_mansion_hall with slideawaydown # 저택 거실 과거
    "저택의 내부는 매우 넓었다."
    "설마 내가 이런곳에서 살거라곤 생각도 못해봤다."
    "하지만 그걸 현실에서 보니 정말 이상한 기분이 들었다."
    show mary
    mary"정말 멋있는거 같아"
    edward"어……"
    "내 입에선 감탄사만 나왔다."
    "외관도 그랬지만, 내부도 정말 엄청났다."
    "정말 TV에서 나올법한 부자집이였다."
    edward_think"도대체 얼마를 쓴걸까……"
    "주변을 둘러보는데 내 눈에 들어오는 게 있었다."
    edward"저거 그랜드 피아노 아니야?"
    mary"아!{cps=2} {/cps}그거 말해주려고 했는데"
    mary"내가 카탈로그를 훑어 보다가 싸게 팔길래 바로 질렀어"
    edward"충동 구매를 했다는 거냐……"
    mary"충동 구매 같은거 아니야!"
    mary"언젠간 쓸일이 있을지도 모르잖아"
    edward"피아노를?"
    mary"그보다 다른방에도 가보자!"
    edward"말 돌리지마!"
    scene black with dissolve
    nvl clear
    narrator_nvl"나랑 메리는 집안 곳곳을 돌아다니며"
    narrator_nvl"각 방을 어디에 사용할지 정했다."
    scene bg test2 with slideleft # 할아버지의 방
    show mary
    mary"여길 침실로 사용 하려고 하는데 어때?"
    edward"괜찮을거 같은데"
    mary"그럼 당장 카탈로그에서 좋은거 하나 찾아보자!"
    edward"또 충동구매 하거나 하진 말고"
    mary"글쎄 걱정 말래두!"
    scene bg mansion_emptyroom with slideawayup
    show mary
    edward"이 방은 어디에 사용할건데?"
    mary"여긴 아직 생각해보질 못했어"
    edward"음……"
    edward_think"창고는 따로 있으니까 필요 없고……"
    edward_think"손님방 같은걸로 사용하면……"
    mary"나중에 나올 아기의 방은 어때?"
    show effect1
    play sound "se/shock.ogg"
    edward"{size=40}아,{cps=2} {/cps}아기?{/size}" with lshake
    hide effect1
    "어째서인지 나는 아기라는 말에 가슴이 두근 거렸다."
    "아무래도……{cps=2} {/cps}더이상 남일 같이 느껴지지가 않아서 그런듯 하다."
    mary"자기가 그렇게 당황하면 나까지 당황하게 되잖아!"
    edward"누누누가 당황을 했다고?!"
    mary"지금도 하고있네"
    edward"그런거 아니야!"
    edward"그리고 그렇게 아기라는 말을 함부로 하지마!"
    edward"난 부모가 돼보는 게 처음이라서 엄청 긴장된다고……"
    mary"부모가 되어보는 건 나도 처음인 걸!"
    mary"하지만……{cps=2} {/cps}나도 그렇고……{cps=2} {/cps}자기도 그렇고……"
    mary"다 그렇게 해서 태어나는 거잖아……"
    edward"왜 얘기가 그쪽으로 흘러가는거야;;"
    mary"어머!{cps=2} {/cps}내가 무슨 말을!"
    edward"뭔가 대화가 이상한 쪽으로 가고있는거 같으니까 여기서 그만두자……"
    mary"좋은 생각이야;;"
    edward"그럼 여긴 언젠간 나올 아기의 방으로 결정!"
    edward"빨리 다음 방으로 출동!"
    mary"후훗"
    edward"왜 그래?"
    mary"\'출동\'이라니"
    mary"뭔가 자기답지 않은 대사 같아서"
    edward"그,{cps=2} {/cps}그건 또 무슨 뜻이야;;"
    mary"자기가 너무 귀엽다는 뜻이야"
    edward"그냥 빨리 가자;;"
    scene black with dissolve
    play music "bgm/beat2.mp3"
    nvl clear
    narrator_nvl"1961년 4월 3일 월요일"
    narrator_nvl"에드워드 토머 28세"
    narrator_nvl"날씨 - 평범"
    nvl clear
    narrator_nvl"난 오늘 모든 짐을 새로 살게될 저택으로 옮겼다."
    narrator_nvl"막상 가구를 배치 해보니까 처음 왔을때만큼 넓게 느껴지진 않았다."
    narrator_nvl"그래도 내 인생에서 이렇게 넓고 좋은 풍경을 지닌 집에서 살아보는 건 처음이다."
    narrator_nvl"매일이 이렇게 평화로웠으면 좋겠다."
    centered"오전 11시 40분"
    scene bg diary_mansion_hall with dissolve # 저택 과거
    edward"영차!"
    edward"이걸로 다 끝난건가?"
    show mary
    mary"자기 정말 수고했어"
    edward"뭐 이걸 가지고"
    mary"오늘 쉬지도 않고 계속 짐만 옮겼잖아"
    edward"몇년간 반복된 노가다 덕분에 이정도 가지곤 힘들지도 않아!"
    mary"그래도 그냥 사람 부르면 될 걸……"
    edward"사람까지 불러버리면 돈 들잖아……"
    mary"그게 얼마 한다고"
    edward"저택 짓는거랑, 자기의 충동 구매 덕분에 지금 꽤 많은 돈을 썼어"
    edward"그리고 \'이케아(Ikea)\'가 얼마나 비싼지 알아?"
    edward"아무리 자기라도 소비는 여기까지만"
    mary"알았어……"
    edward"그나저나 여긴 경치가 진짜 끝내준다~"
    mary"그치?"
    mary"막 힘들었던 일이 전부 사라지는 느낌이지?"
    edward"응?"
    edward"그게 무슨……?"
    mary"자기는 힘들때 마다 이 절벽 근처에 와서 풍경을 바라보곤 했잖아!"
    mary"여기서 풍경을 보고있으면 힘들었던 일이 전부 잊어진다고 했지?"
    edward"맞긴 맞지만……"
    edward_think"그걸 어떻게 안거지?"
    edward_think"내가 메리한테 말한적이 있었나?"
    mary"왜 그래?"
    edward"아무것도 아니야"
    edward"그보다 오늘 점심은 뭐야?"
    mary"오늘은 이사 기념으로 바베큐를 먹을까 싶어"
    stop music
    edward"바베큐라……"
    edward"안 먹은지 꽤 오래된거 같네……"
    mary"그래?"
    edward"어……"
    play music "bgm/sad2.mp3"
    edward"마지막으로 먹었을때가 아마 내가 아주머니 댁에서 살고 있을때 였을거야……"
    mary"아주머니?"
    edward"혹시 내가 말 안 해줬던가?"
    mary"예전에 한번 들어본적이 있었던거 같긴해……"
    mary"근데 자기한테서 직접 들은적은 없어"
    mary"아주머니는 어떤 분이셔?"
    edward"그 분은……"
    edward"어렸을때 부터 날 키워주신 분이야"
    mary"어렸을때……?"
    edward"응"
    extend", 내 부모님은 일 때문에 해외에 계셔서……"
    edward"어쩔 수 없이 엄마의 아는 분이랑 같이 생활하게 됐지"
    mary"정말 처음듣는 이야기네……"
    mary"난 에드워드에 대해서 아는 게 별로 없었구나……"
    edward"너무 우울해 하진 마!"
    edward"난 괜찮으니까!"
    edward"그보다 빨리 먹으러 가자!"
    mary"그래"
    scene black with dissolve
    nvl clear
    narrator_nvl"나의 인생은 정말 한동안 평화로웠다."
    narrator_nvl"회사 상태가 그렇게 뛰어나게 좋은건 아니지만 그래도 우린 나름 부자였고"
    narrator_nvl"난 메리랑 결혼 했고"
    narrator_nvl"이렇게 큰 저택에서 살고"
    narrator_nvl"메리의 병은 눈에 띄지 않을 정도로 좋아졌고"
    narrator_nvl"정말 이 이상 행복해 질 수 있을까 의문이다."
    play music "bgm/smooth3.mp3"
    nvl clear
    narrator_nvl"1963년 6월 7일 금요일"
    narrator_nvl"에드워드 토머 29세"
    narrator_nvl"날씨 - 맑음"
    nvl clear
    narrator_nvl"오늘은 병원에 새로운 의료기기가 왔다며 통지가 왔다."
    narrator_nvl"이 걸 이용하면 기존 방식에 비해 몇 10배는 더 정확한 결과를 얻을 수 있다고 한다."
    narrator_nvl"메리의 상태가 많이 좋아졌기에 결과는 뻔히 보였지만"
    narrator_nvl"그래도 장인 어른의 희망 사항이니 난 어쩔 수 없이 메리를 데리고 병원으로 갔다."
    scene bg diary_hospital_med with dissolve
    edward"안녕하세요."
    doc"이거 정말 오랫만에 뵈는군요."
    doc"그동안 아내분의 상태는 괜찮았는가요?"
    edward"네,{cps=2} {/cps}기침도 많이 줄어들고, 몸도 괜찮은거 같고"
    doc"많이 줄었다는 건 기침을 아직도 하긴 한다는 뜻이가요?"
    edward"네……"
    edward"아주 가끔 조금씩 해요."
    doc"그렇군요."
    doc"여기 오신 이유가 이번에 새로 들어온 방사선 검사기를 이용하기 위해서가 맞나요?"
    edward"네"
    doc"검사하는데 좀 걸릴테니 그동안 밖에서 기다려 주세요."
    edward"알겠습니다."
    show mary
    edward"검사 잘해"
    mary"응"
    hide mary
    play sound "se/footsteps_concrete.mp3"
    $ renpy.pause(3)
    play sound "se/door_open.ogg"
    scene bg diary_hospital_hall with slideleft
    "나는 메리가 검사를 받는동안 복도에서 기다리기로 했다."
    "괜찮은 결과가 나올거라 믿곤 있지만"
    "그래도 불안한 마음이 없는 건 아니다."
    scene black with slideawayleft
    stop music
    centered"35분 후"
    scene bg diary_hospital_hall with slideright
    $ extra_name = '간호사'
    extra"에드워드 토머님,{cps=2} {/cps}선생님 께서 부르십니다."
    edward"네"
    play sound "se/door_open.ogg"
    scene bg diary_hospital_med with blinds
    play music "bgm/sad2.mp3"
    doc"여기 앉아주세요."
    "나는 선생님이 시키신 데로 앞에있는 둥근 의자에 앉았다."
    edward"메리의 상태는 어떤가요?"
    doc"그게……"
    doc"3년 전이랑 크게 바뀐게 없습니다."
    edward"바뀐게 없다면……{cps=2} {/cps}전혀 개선되지 않았다는 뜻인가요?"
    doc"네……"
    show mary at right
    mary"하지만 3년 전이면 제가 괜찮아졌다고 했으니까"
    mary"그때랑 차이가 없다고 해서 위험한 건 아니잖아요."
    doc"말씀대로 몸이 나빠지거나 한건 아니니까 걱정할 건 없지만"
    doc"제가 걱정인건 바로 \'잠복기\'입니다."
    edward"\'잠복기\'……?"
    doc"암 세포가 한동안 잠잠해지는 기간을 의미합니다."
    doc"암 말기에 세포가 잠복기에 들어가는 건 저도 처음 들어 보긴 하지만……"
    doc"사실 저희 나라에서 암 보단 결핵에 의한 사망률이 더 높다 보니까……{cps=2} {/cps}전례가 부족한것도 어쩌면 당연하죠……"
    edward"어쨌건, 잠복기에 들어갔다는 뜻은 나중에 더 심각해 질 수가 있다는 뜻인가요?"
    doc"그럴수도 있고……{cps=2} {/cps}어쩌면 그 상태 그대로 죽을때까지 유지 될수도 있습니다."
    edward"그럴수가……"
    doc"그래도 후자의 경우 고통은 적습니다."
    edward"고통이 적다고 해도 병이 완전히 낫는 건 아니잖아요."
    mary"여보"
    mary"난 괜찮아"
    mary"난 병이 치료 되든 안되든 별로 신경 안써"
    mary"그러니까 자기도 너무 걱정하지 마"
    edward"그래도……"
    mary"이걸로 검사는 전부 끝난건가요?"
    doc"네……"
    mary"빨리 돌아가자!"
    edward"그래……"
    edward_think"정말 이대로 괜찮은 걸까……"
    "나는 마음속으로 괜히 불안해졌다."
    scene black with dissolve
    play music "bgm/beat4.mp3"
    nvl clear
    narrator_nvl"1963년 9월 20일 금요일"
    narrator_nvl"에드워드 토머 30세"
    narrator_nvl"날씨 - 바람이 조금씩 붐"
    nvl clear
    narrator_nvl"오늘은 내 생일이다!"
    narrator_nvl"근데 옛날처럼 기쁘진 않다."
    narrator_nvl"생일날엔 뭔가 특별한걸 받는것도 아니고……"
    narrator_nvl"그냥 나이만 한살 더 먹고……"
    narrator_nvl"뭐, 딱히 특별한게 받고 싶거나 그런건 아니지만"
    centered"오전 6시 반"
    scene bg test2 with dissolve # 둘의 침실 배경
    play bgs "bgs/birds.mp3"
    edward"후아아암~"
    edward"좋은 아침이다."
    "이곳의 아침은 언제나 상쾌하다."
    "옆엔 내 사랑 메리가 있고, 새 소리가 들려오고"
    "또 내 생일이고……"
    edward"여보 일어나"
    mary"응……?"
    show mary with dissolve
    mary"왠일로 이렇게 일찍 일어났어……?"
    edward"오늘이 무슨 날인지 알아?!"
    mary"어……"
    mary"오늘 금요일 이잖아"
    edward"또?"
    mary"9월달의 20번째 날?"
    edward"으……"
    edward_think"설마 내 생일을 기억 못하는 건가?!"
    edward_think"아니야!{cps=2} {/cps}어쩌면 서프라이즈를 위해서 일부러 저러는 걸 수도 있어!"
    edward"마,{cps=2} {/cps}맞아!!"
    edward"오늘은 출근 하는 날이니까 빨리 일어나서 출근 준비 하자!"
    mary"무슨 바람이 불었길래 먼저 출근 하자는 소리를해……"
    mary"설마 진짜로 바람이?!"
    edward"그럴 리가 없잖아!!"
    mary"하긴……"
    mary"자기는 회사에서 인기가 없으니까"
    edward"윽……"
    edward"그보다 빨리 아침밥 해줘……"
    mary"부엌 서랍 두번째 칸에 시리얼 있으니까 그걸로 먹어……"
    mary"후아암……"
    mary"난 다시 잘래……"
    hide mary with dissolve
    edward"어……"
    show effect1
    play sound "se/shock.ogg"
    edward_think"{size=40}뭐지?!{/size}" with lshake
    edward_think"설마 벌써 권태기가?!"
    hide effect1
    edward_think"몇년 전까지만 해도 먼저 일어나고……"
    edward_think"맨날 밥을 해줬고……"
    edward_think"심지어 아무리 내가 싫다고 해도, 밥까지 먹여줬던 사람이!"
    edward_think"새월이 야속해……"
    stop bgs
    scene black with dissolve
    centered"오후 3시"
    scene bg employee_office_day with blinds
    "나는 일을 하고있는 메리를 바라보며 이런 저런 생각을 했다."
    edward_think"설마 내 생일을 잊어버린건 아니겠지?!"
    edward_think"난  매년 메리의 생일을 챙겨 줬는데……"
    edward_think"참 너무하네……"
    edward_think"한번 직접 물어볼까……?"
    play sound "se/footsteps_concrete.mp3"
    $ renpy.pause(3)
    "나는 메리에게 다가갔다."
    show mary
    mary"이건 이렇게 하는 거예요."
    $ extra_name = '직원'
    extra"오오……{cps=2} {/cps}그렇군요."
    mary"이제 혼자서도 할 수 있겠죠?"
    extra"네!"
    extra"감사합니다."
    edward"…………"
    mary"어?{cps=2} {/cps}에드워드?"
    edward"잠깐 시간좀 있어?"
    mary"음……"
    mary"미안,{cps=2} {/cps}지금은 좀 바뻐서……"
    mary"혹시 퇴근한 다음엔 안돼나?"
    edward"으,{cps=2} {/cps}응……"
    edward_think"그냥 포기하자……"
    scene bg employee_lounge with slideleft
    "나는 커피를 한잔을 들고 직원 휴개실에서 잠깐 쉬고 있었다."
    "오늘은 어쩐지 주변에서 나를 험담하는 소리가 안들린다."
    edward_think"하긴……{cps=2} {/cps}이 회사에 들어온지 몇년이나 지났으니까"
    edward_think"이제 질린만도 하겠지"
    edward"어휴……"
    "나는 혼자서 한숨을 쉬기만 했다."
    "그때 직원 휴개실에서 꽤 많은 사람의 발소리가 들려왔다."
    $ extra_name ='직원'
    extra"안녕하십니까!{cps=2} {/cps}회장님!"
    edward_think"회장님?"
    "나는 발소리가 들려오는 쪽으로 고개를 돌렸다."
    "거긴 꽤 많은 사람과 함께 메리의 아버님이 걸어 오고 있었다."
    $ extra_name='메리의 아버님'
    extra"여기가 내가 말한 곳인데 어떤가?"
    $ extra_name = '건설 업채 사람'
    extra"전 정말로 맘에 듭니다!"
    extra"작업은 언제부터 하면 괜찮을까요?"
    $ extra_name='메리의 아버님'
    extra"하루면 전부 끝낼수 있다고 했나?"
    $ extra_name='건설 업채 사람'
    extra"넵"
    extra"그다지 설치할게 많진 않으니까요."
    $ extra_name='메리의 아버님'
    extra"내일은 주말이니 그때부터 작업을 부탁하네"
    $ extra_name='건설 업채 사람'
    extra"알겠습니다!"
    "나는 혹의심에 메리의 아버님에게 말을 걸었다."
    edward"회장님,{cps=2} {/cps}무슨 일 있으신가요?"
    $ extra_name = '메리의 아버님'
    extra"오,{cps=2} {/cps}에드워드"
    extra"여기에 매점을 하나 설치할 예정인데 어떤가?"
    edward"매점이요?"
    extra"그래"
    extra"휴개실이 많이 심심하거 같아서 말이지"
    edward"확실히……"
    edward"마실게 커피밖에 없으니까요."
    $ extra_name = '건설 업채 사람'
    extra"이분은……?"
    $ extra_name = '메리의 아버님'
    extra"아,{cps=2} {/cps}이거 내가 실례 했구만"
    extra"이 사람이 바로 내 사위라네!"
    $ extra_name='건설 업채 사람'
    extra"아!{cps=2} {/cps}그렇군요!"
    extra"만나서 정말 반갑습니다!"
    edward"네,{cps=2} {/cps}저야말로……"
    extra"혹시 휴개실은 자주 들리시나요?"
    edward"뭐,{cps=2} {/cps}가끔 들리는 편입니다."
    extra"그렇군요."
    extra"앞으로도 자주 만나 뵀으면 좋겠네요."
    edward"저도요."
    extra"그럼 회장님,{cps=2} {/cps}저는 이만 가보겠습니다."
    $ extra_name = '메리의 아버님'
    extra"그래,{cps=2} {/cps}조심히 가게나"
    play sound "se/footsteps_concrete.mp3"
    $ renpy.pause(3)
    "건설 업채에서 온 사람은 나갔다."
    edward_think"생각해보니까 지금 장인 어른이랑 같이 있네?!"
    edward_think"이걸 기회로 메리에 대해서 한번 물어볼까……?"
    edward_think"근데 뭔가 좀 어색하네……"
    edward_think"역시 장인 어른과 단 둘이 있어서 그런 걸까……"
    extra"음……{cps=2} {/cps}자네……?"
    edward"넵!"
    extra"그렇게 긴장 하진 말게나"
    edward"아,{cps=2} {/cps}네"
    extra"요즘 메리랑 잘 지내고 있나?"
    edward"뭐 그렇죠……"
    edward"메리도 많이 건강해져서 같이 일상 생활을 하는데 더 편해졌고……"
    edward"근데……"
    edward"그거 때문인지 최근에 메리가 많이 무덤덤 해진거 같아요."
    extra"무덤덤이라니?"
    edward"그냥……{cps=2} {/cps}옛날과 많이 변했다고 할까……"
    extra"아……"
    extra"허허허"
    extra"그런건가"
    extra"결혼을 오래동안 하다 보면 그런일이 있을 수 있지"
    extra"생각 해보니까 오늘 자네 생일이 아닌가?"
    edward"알고 계셨나요?"
    extra"아무리 나이가 있어도, 남의 생일을 잊을 정도로 늙진 않았네!"
    edward"아,{cps=2} {/cps}죄송합니다!"
    extra"허허허"
    extra"아까 무덤덤이라고 했던게 혹시 메리가 자네 생일을 기억 못하고 있어서?"
    edward"뭐……{cps=2} {/cps}그런 거죠……"
    edward_think"우와,{cps=2} {/cps}정확하다."
    extra"좋아,{cps=2} {/cps}내가 도와주도록 하겠네"
    edward"아,{cps=2} {/cps}그러실 필요는……"
    extra"아니야,{cps=2} {/cps}내가 자네였어도 같음 심정이였을게야"
    extra"그 마음 잘 이해 하네"
    extra"메리가 일 할땐 뛰어나지만 사적인 일에선 많이 떨어지는 편이거든"
    extra"자네가 최고의 생일을 보낼수 있도록 내가 돕겠네"
    edward"감사합니다……"
    edward_think"어떻게 도움을 줄지 참 궁금하네……"
    play sound "se/footsteps_concrete.mp3"
    $ renpy.pause(3)
    "메리의 아버님은 사무실 쪽으로 이동을 했다."
    "내가 할 수 있는거라곤 그저 기다리는것 뿐이었다."
    scene bg employee_office_night with squares
    "퇴근 시간이 되었다."
    "나는 메리랑 같이 퇴근을 하기 위해 메리의 책상으로 이동을 했지만……"
    edward"메리?"
    $ extra_name = '직원'
    extra"사장님 이라면 먼저 퇴근 하셨는데요?"
    play music "bgm/sad3.mp3"
    edward_think"먼저 퇴근을 했다고?!"
    edward"어,{cps=2} {/cps}알려줘서 고마워"
    edward_think"뭐지……"
    edward_think"왜 오늘은 평상시랑 다르게 먼저 갔을까?"
    edward_think"혹시 내 선물을 사주기 위해?!"
    play sound "se/shock2.mp3"
    show effect2
    edward_think"그럴 리가 없지……"
    hide effect2
    edward"어휴……"
    edward_think"그냥 나도 돌아가야겠다."
    scene black with dissolve
    "나는 혼자서 걸어가며 \'벌써 권태기가 온건가?\',\'내가 무슨 실수를 했나?\',\'설마 내가 질린건가?\'등"
    "이런저런 생각을 했다."
    "하지만 난 메리를 단 한번도 의심 하진 않았다."
    "의심하고 싶진 않았다."
    "솔직히 최악의 시나리오를 떠올린 적이 없다고는 말 못한다."
    "그래도 금방 부정을 하고 다른 생각을 하려고 노력을 했다."
    edward_think"그래!"
    edward_think"집에 돌아가면 무족건 사과를 하는거야!"
    edward_think"언제나 적극적이었던 메리가 이렇게 차갑게 구는 건 역시 내가 문제였어!"
    edward_think"메리가 날 떠나는 건 원치 않다고!"
    centered"오후 6시 40분"
    scene bg diary_mansion_hall with slidedown
    edward"메리?"
    "나는 집에 들어와서 메리를 찾았다."
    play sound "se/footsteps_wood.mp3"
    $ renpy.pause(3)
    "윗층에서 누군가 내려오는 소리가 들렸다."
    show mary
    mary"왔어?"
    edward_think"사과를 하는거야……"
    edward"메리 정말 미안해!"
    mary"응?"
    edward"솔직히 말해서 내가 뭘 잘못했는지 잘은 모르겠지만"
    edward"앞으론 잘할게!"
    edward"그러니까……"
    mary"어……?"
    mary"갑자기 무슨 소리야;;"
    edward"요즘 자기의 기분이 많이 안좋잖아"
    edward"얼마 전까지만 해도 나보다 일찍 일어나고……"
    edward"아침밥도 자주 안 차려줬고"
    stop music
    mary"나……{cps=2} {/cps}평상시랑 크게 바뀐게 없는데;;"
    mary"어젠 내가 일찍 일어나서 차려 줄 수 있었지만 주말엔 거의 알아서 해 먹었잖아"
    mary"아무래도 오늘이 자기 생일 이니까 너무 기대한게 많아서 그런게 아닐까?"
    edward"생일?"
    show effect1
    play sound "se/shock.ogg"
    edward"{size=40}혹시 오늘이 내 생일 인거 알고 있었어?!{/size}" with lshake
    hide effect1
    mary"음……"
    mary"그거에 관해서 나도 미안한게 있어"
    mary"사실 내가 아무런 선물을 준비 못해서……"
    play sound "se/think.mp3"
    show ev ribbon_mary
    "메리는 주머니에서 꽃 형태의 리본 핀을 머리에 꽂았다."
    play music "bgm/beat4.mp3"
    show effect1
    play sound "se/shock.ogg"
    mary"내가 오늘 자기의 선물이 되려고!" with lshake
    hide effect1
    edward"…………"
    mary"뭐,{cps=2} {/cps}뭐라도 말해봐……"
    mary"이거 엄청 민망 하다고……"
    edward"풉"
    mary"우,{cps=2} {/cps}웃지마!"
    edward"미안"
    edward"정말 다행이라고 생각해서……"
    mary"그래……?"
    edward"후후"
    scene black with dissolve
    "나는 메리를 꼭 껴안으며 귓가에 속삭였다."
    edward"지금까지 내가 받은 선물중 최고의 생일 선물이야~"
    mary"어……{cps=2} {/cps}벼,{cps=2} {/cps}별말씀을"
    mary"그렇게 꼭 껴안으면 나 숨막혀……"
    edward"내 생일 선물이니까 마음대로 해도 되는거지?"
    mary"어,{cps=2} {/cps}어?!"
    ################################1963년 9월 20일 일기장 끝############################
    scene bg lib_day with memory
    centered"오전 11시 10분"
    show stephan smile2
    stephan_think"므흣"
    stephan_think"참 즐거운 생활을 하셨네"
    show stephan shock
    stephan_think"잠깐?"
    stephan_think"생각 해보니까 오늘 9월 20일 아닌가?"
    "나는 재대로 확인을 하기 위해서 폰을 봤다."
    show effect1
    play sound "se/shock.ogg"
    stephan_think"{size=40}그럼 오늘 할아버지 생일 이었던거야?!{/size}" with lshake
    stephan_think"이거 큰일 났군"
    hide effect1
    hide stephan shock
    play sound "se/footsteps_wood.mp3"
    $ renpy.pause(3)
    play sound "se/door_open.ogg"
    scene black with dissolve
    $ renpy.pause(0.5)
    scene bg mansion_hall with slidedown
    show stephan talk at left
    stephan"시아!"
    stephan"혹시 오늘 할아버지 생신인거 알고 있었어?"
    cia"네"
    cia"설마 도련님은 모르고 계셨나요?!"
    show stephan shock at left
    stephan"음……"
    stephan"그,{cps=2} {/cps}그건……"
    hide stephan shock
    menu:
        "사실 깜빡하고 있었어(진실)":
            show stephan talk at left
            stephan"사실 오늘 생신이 걸 깜빡했어……"
            cia"그럼 할아버님께 드릴 선물이 없겠네요?"
            stephan"응……"
            cia"그럼 제 선물을 같이 드려요!"
            show stephan at left
            stephan"정말?"
            cia"네!"
            cia"힘들땐 서로 도와야죠"
            stephan"정말 고마워"
            cia"아니에요."
            cia"할아버님도 저 혼자서 준비 한 것보단 도련님이 같이 준비했다고 하는편이 더 좋아 하실듯 하니까요."
            stephan_think"생각 하는 게 완전 천사야!"
            stephan"근데 선물로 뭘 준비 했어?"
            cia"할아버님이 쓰고 계시는 안경 있잖아요?"
            cia"꽤 낡은거 같아서 제가 새로운걸로 사왔어요."
            cia"도수는 할아버지걸로 맞춰져 있으니까 바로 끼실수 있을거예요."
            stephan"그거 괜찮은 선물이네!"
            cia"그쵸?"
            stephan"응"
            stephan"정말 오늘 시아 덕분에 살았어……"
            cia"에이~{cps=2} {/cps}별말씀을"
            stephan"근데 생일 선물은 언제 전해줄 생각이야?"
            cia"세바스찬이 점심시간에 맞춰서 케이크를 사오겠다고 해요."
            cia"그래서 그때 케이크랑 같이 할아버지께 전해줄 예정입니다!"
            show stephan smile at left
            stephan"알았어!"
            stephan"그때 까지 내가 도와줄거 있어?"
            cia"흠……"
            cia"생일 파티를 위해 부엌에 장식을 다는거 도와주시면 고마울거 같아요."
            stephan"오케이"
            scene black with slideleft
            centered"오후 1시"
            scene bg mansion_hall with moveup
            play sound "se/door_knock.mp3"
            $ renpy.pause(1)
            cia"네~{cps=2} {/cps}갑니다~"
            play sound "se/door_open.ogg"
            seb"영차"
            seb"여기 케이크 사왔어요."
            cia"어머,{cps=2} {/cps}케이크가 정말 맛있어 보이네요!"
            seb"그쵸?"
            cia"비싸 보이는데 괜찮았어요?"
            seb"아는 사람이 근처에서 제과점을 해서 가격을 좀 깎아서 받았어요."
            cia"역시 세바스찬이에요!"
            seb"…………"
            play sound "se/footsteps_wood.mp3"
            $ renpy.pause(3)
            show stephan talk at left with dissolve
            seb"도,{cps=2} {/cps}도련님!"
            seb"오셨습니까?!"
            stephan"어,{cps=2} {/cps}세바스찬도 어서와."
            stephan"근데 얼굴이 왜그렇게 빨게?"
            seb"아,{cps=2} {/cps}아무것도 아니에요!"
            stephan"그래?"
            show stephan at left
            stephan"그보다 그거 생일 케이크지?"
            stephan"맛있는 걸로 사왔네!"
            seb"네!"
            seb"또, 이 케이크가 글루텐이 없어서 할아버님이 드셔도 괜찮아요!"
            stephan"오오!"
            cia"준비도 전부 끝났으니까 이제 할아버님을 데리고 올게요!"
            play sound "se/move.mp3"
            scene black with slideright
            stop music
            $ renpy.pause(0.5)
            play sound "se/move.mp3"
            scene bg test2 with slideright # 부엌 배경
            centered"할아버지의 생일 파티"
            "시아는 할아버지의 눈을 살짝 가리면서 테이블 쪽으로 안내했다."
            "근데 들어오는 할아버지의 모습에서 알수없는 위화감이 느껴졌다."
            "평상시엔 양손으로 쥐던 지팡이를 오늘은 오른손으로만 쥐어서 그런걸까?"
            cia"{size=25}하나 둘……{/size}"
            $ extra_name = '모두'
            play sound "se/shock.ogg"
            play music "bgm/beat5.mp3"
            show effect1
            extra"{size=45}할아버지!{cps=2} {/cps}생신 축하 드려요!{/size}" with lshake
            hide effect1
            grandpa"어……?"
            cia"작년엔 할아버님께서 됐다고 하셨지만"
            cia"올해는 꼭 뭔가를 해드리고 싶었습니다!"
            cia"그래서 다같이 이렇게 깜짝 파티를 하기로 결정했어요!"
            seb"뭐……{cps=2} {/cps}거의 시아 혼자서 생각 한거지만……"
            grandpa"다들……"
            grandpa"정말 고맙구나……"
            seb"저희야 말로 정말 고맙습니다."
            cia"네,{cps=2} {/cps}할아버님 덕분에 저희가 얼마나 기쁜데요!"
            show stephan at left
            stephan"좀 세삼스럽지만……"
            stephan"어렸을때도 그랬고, 지금도 정말 감사합니다."
            grandpa"아니……"
            grandpa"나야말로 정말 고맙다……"
            grandpa"사실 나도 내 생일을 까먹고 있었는데……"
            hide stephan
            cia"할아버님!{cps=2} {/cps}아직 감동받기엔 이르다구요."
            cia"에헴……"
            cia"{size=45}그럼 지금부터 생일 선물을 주는 시간이 있겠습니다!{/size}"
            play sound "se/search_bag.mp3"
            $ renpy.pause(2)
            cia"짜잔!"
            "시아는 밝은 포장지로 포장 되어있는 선물을 할아버지한테 건냈다."
            cia"한번 열어 보세요!"
            grandpa"그래……"
            grandpa"근데 시아……"
            grandpa"이 포장지 좀 대신해서 뜯어 줄 수 있을까?"
            grandpa"내가 손톱을 깎아서 말이지……"
            cia"네!"
            "할아버지는 한손으로 들고 있던 선물을 다시 시아에게 건냈다."
            "시아가 할아버지를 대신해서 포장지를 뜯자 그 안엔 갈색 가죽으로 된 안경 케이스가 있었다."
            grandpa"이건……"
            cia"저랑 스테반 도련님이 같이 준비 한거예요."
            cia"할아버님 안경이 꽤 오래 되셨잖아요!"
            cia"그래서 같이 새걸로 사드리기로 결정 했어요."
            grandpa"정말 고맙구나 시아, 스테반……"
            cia"도수도 맞춰져 있으니까 바로 껴 보실수 있을거예요."
            grandpa"그럼 당장 껴 봐야겠네"
            "할아버지는 자신이 끼고 있던 안경을 벗고 새로운걸 착용했다."
            grandpa"어떠냐?"
            show stephan at left
            stephan"정말 잘 어울려요!"
            hide stephan
            seb"그리고 할아버님, 이건 제가 드리는 선물입니다."
            seb"시아랑 도련님것보단 형편이 없을지도 모르겠지만……"
            "세바스찬은 테이블 밑에서 케이크가 든 상자를 꺼냈다."
            seb"생신 축하드립니다."
            grandpa"생일 케이크라……"
            seb"할아버님의 연새가 올해 들어서 81세 시죠?"
            grandpa"벌써 그렇게 됐구나……{cps=2} {/cps}허허……"
            "세바스찬은 긴 초 8개랑 짧은 초 1개를 케이크 위에 꽂았다."
            "그리고 라이터로 각 촛불에 불을 붙히면서 할아버지 한테 말했다."
            seb"생일 하면 역시 초불을 끄면서 비는 소원이죠"
            grandpa"이거 이거……"
            grandpa"이 나이가 되서 이런걸 하게 될줄이야"
            seb"무언가를 축하하는데 나이가 무슨 상관이겠습니까?"
            grandpa"하긴"
            grandpa"그럼……"
            "할아버지는 숨을 크게 들이 쉬더니 케이크 위에 있던 촛불을 향해서 바람을 불었다."
            "두번 정도 숨을 불어 넣었더니 촛불이 전부 꺼졌다."
            play sound "se/clapping.mp3"
            "우리는 할아버지의 생신을 축하하며 박수를 쳤다."
            seb"할아버님은 생일로 어디 가고 싶으신 곳 있으세요?"
            grandpa"괜찮아"
            grandpa"난 이정도면 충분히 만족 했단다……"
            grandpa"내 생일을 마지막으로 축하 받은 게 몇년전 이었냐면……"
            grandpa"아무튼, 엄청 오래됐었지"
            grandpa"이렇게 다시 생일을 축하 받으니까 정말 기쁘구나"
            grandpa"정말 옛날 생각이 많이 났어……"
            grandpa"그럼 세바스찬이 준비한 케이크를 빨리 먹자구나"
            scene black with dissolve
            "우리 넷은 케이크를 나눠 먹고, 떠들면서 즐거운 시간을 보냈다."
            "하지만 할아버지는 옆에서 가만히 우리를 지켜보며 만족스러운 미소를 띄기만 했다."
        
        "나도 알고 있었어!(거짓)":
            if  persistent.ending1 == 2:
                $ persistent.ending1 += 1
            show stephan shock2 at left
            stephan"나,{cps=2} {/cps}나도 알고 있었어!"
            stephan"그냥 시아는 알고 있었나 싶어서 물어 본거야"
            cia"아,{cps=2} {/cps}그랬군요."
            cia"제가 실례 했습니다……"
            stephan"아,{cps=2} {/cps}아니야!"
            show stephan at left
            stephan"시아는 생일 선물로 뭘 준비 했어?"
            cia"비밀이에요."
            show stephan shock2 at left
            stephan"그,{cps=2} {/cps}그래?"
            stephan"그럼 내 선물도 비밀~"
            stephan_think"이걸로 내가 사실은 선물을 준비하지 못했다는 건 틀키지 않은건가……"
            show stephan at left
            stephan_think"친손자의 선물이 형편 없어서야 안돼지!"
            stephan_think"할아버지를 위한 최고의 생일 선물을 생각 해봐야겠어!"
            cia"도련님"
            show stephan shock2 at left
            show effect1
            play sound "se/shock.ogg"
            stephan"{size=40}ㅇ,{cps=2} {/cps}왜?!{/size}" with lshake
            hide effect1
            cia"왜그렇게 당황 하세요?"
            stephan"아무것도 아니야!"
            stephan"그냥 다른 생각 중이었거든"
            cia"혹시 시간 되시면 같이 꾸미는거 좀 도와 주실 수 있을까요?"
            stephan"꾸민다니?"
            cia"할아버지 생일 파티를 위해서 부엌을 좀 장식 하려구요."
            stephan"그,{cps=2} {/cps}그래!"
            stephan"도와줄게!"
            show stephan shock at left
            stephan_think"시간이 가기 전에 빨리 선물로 줄만한걸 찾아봐야 겠어"
            scene bg test2 with blinds # 부엌 배경
            play sound "se/search_bag.mp3"
            "나랑 시아는 부엌에 간단한 장식을 달고 있었다."
            "시아는 휫파람까지 불어가며 즐겁게 하고 있지만"
            "난 생일선물 생각으로 머릿속이 가득했다."
            show stephan think
            stephan_think"뭐가 좋을까……"
            stephan_think"당장 내가 준비 할 수 있고, 할아버지의 인상에 확 남을 법한 선물이……"
            cia"도련님"
            cia"저기 상자 안에 있는 리본 좀 주세요."
            show stephan talk at left
            stephan"그래……"
            "나는 상자 안에서 돌돌 말려있는 붉은색 리본을 손에 쥐었다."
            "그때 내 머릿속에서 좋은 아이디어가 스쳐 지나갔다."
            show stephan
            stephan_think"이거야!"
            show stephan smile2
            stephan_think"이거면 분명 할아버지한테 강한 인상을 남겨 줄지도 몰라!"
            stephan"흐흐흐흐……"
            hide stephan smile2
            cia"도,{cps=2} {/cps}도련님……?"
            show stephan smile at left
            stephan"이 리본좀 빌려도 될까?"
            cia"딱히 상관은 없습니다만……"
            stephan"또,{cps=2} {/cps}헤어 클립이랑 본드 같은거있어?"
            cia"헤어 클립은 왜요?!"
            show stephan shock2 at left
            stephan"내,{cps=2} {/cps}내가 준비한 선물을 포장하는 걸 깜빡 했거든!"
            stephan"묶는데 오래 걸릴거 같아서 헤어클립 위에 리본을 붙이려고!"
            cia"그거 괜찮은 생각이네요."
            cia"본드는 상자 안에 있을거예요."
            cia"헤어 클립은 제가 방에서 가져올게요."
            show stephan smile at left
            stephan"고마워!"
            scene black with moveleft
            stephan_think"할아버지의 인상에서 가장 잘 남을만한 선물을 보여주마!"
            "선물을 준비하는 동안 나도 모르게 엄청난 승부욕이 생겨버렸다."
            "딱히 대회를 하는것도 아니고"
            "멋있는 선물을 준비 했다고 해서 뭔가 얻는것도 아닌데도"
            "괜히 혼자서 불타오르고 있었다."
            centered"오후 1시"
            scene bg mansion_hall with moveup
            play sound "se/door_knock.mp3"
            $ renpy.pause(1)
            cia"네~{cps=2} {/cps}갑니다~"
            play sound "se/door_open.ogg"
            seb"영차"
            seb"여기 케이크 사왔어요."
            cia"어머,{cps=2} {/cps}케이크가 정말 맛있어 보이네요!"
            seb"그쵸?"
            cia"비싸 보이는데 괜찮았어요?"
            seb"아는 사람이 근처에서 제과점을 해서 가격을 좀 깎아서 받았어요."
            cia"역시 세바스찬씨 예요!"
            seb"…………"
            play sound "se/footsteps_wood.mp3"
            $ renpy.pause(3)
            show stephan talk at left
            seb"도,{cps=2} {/cps}도련님!"
            seb"오셨습니까?!"
            stephan"어,{cps=2} {/cps}세바스찬도 어서와."
            stephan"근데 얼굴이 왜그렇게 빨게?"
            seb"아,{cps=2} {/cps}아무것도 아니에요!"
            stephan"그래?"
            show stephan at left
            stephan"그보다 그거 생일 케이크지?"
            stephan"맛있는 걸로 사왔네!"
            seb"네!"
            seb"또, 이 케이크가 글루텐이 없어서 할아버님이 드셔도 괜찮아요!"
            stephan"오오!"
            cia"준비도 전부 끝났으니까 이제 할아버님을 데리고 올게요!"
            play sound "se/move.mp3"
            scene black with slideright
            stop music
            $ renpy.pause(0.5)
            play sound "se/move.mp3"
            scene bg test2 with slideright # 부엌 배경
            centered"할아버지의 생일 파티"
            "시아는 할아버지의 눈을 살짝 가리면서 테이블 쪽으로 안내했다."
            "근데 들어오는 할아버지의 모습에서 알수없는 위화감이 느껴졌다."
            "평상시엔 양손으로 쥐던 지팡이를 오늘은 오른손으로만 쥐어서 그런걸까?"
            cia"{size=25}하나 둘……{/size}"
            $ extra_name = '모두'
            play sound "se/shock.ogg"
            play music "bgm/beat5.mp3"
            show effect1
            extra"{size=45}할아버지!{cps=2} {/cps}생신 축하 드려요!{/size}" with lshake
            hide effect1
            grandpa"어……?"
            cia"작년엔 할아버님께서 됐다고 하셨지만"
            cia"올해는 꼭 뭔가를 해드리고 싶었습니다!"
            cia"그래서 다같이 이렇게 깜짝 파티를 하기로 했죠"
            seb"뭐……{cps=2} {/cps}거의 시아 혼자서 생각 한거지만……"
            grandpa"다들……"
            grandpa"정말 고맙구나……"
            seb"저희야 말로 정말 고맙습니다."
            cia"네,{cps=2} {/cps}할아버님 덕분에 저희가 얼마나 기쁜데요!"
            show stephan at left
            stephan"좀 세삼스럽지만……"
            stephan"어렸을때도 그랬고, 지금도 정말 감사합니다."
            grandpa"아니……"
            grandpa"나야말로 정말 고맙다……"
            grandpa"사실 나도 내 생일을 까먹고 있었는데……"
            hide stephan
            cia"할아버님!{cps=2} {/cps}아직 감동받기엔 이르다구요."
            cia"에헴……"
            cia"{size=45}그럼 지금부터 생일 선물을 주는 시간이 있겠습니다!{/size}"
            cia"이건 제가 준비한거예요!"
            play sound "se/search_bag.mp3"
            $ renpy.pause(2)
            cia"짜잔!"
            "시아는 밝은 포장지로 포장 되어있는 선물을 할아버지한테 건냈다."
            cia"한번 열어 보세요!"
            grandpa"그래……"
            grandpa"근데 시아……"
            grandpa"이 포장지 좀 대신해서 뜯어 줄 수 있을까?"
            grandpa"내가 손톱을 깎아서 말이지……"
            cia"네!"
            "할아버지는 한손으로 들고 있던 선물을 다시 시아에게 건냈다."
            "시아가 할아버지를 대신해서 포장지를 뜯자 그 안엔 갈색 가죽으로 된 안경 케이스가 있었다."
            grandpa"이건……"
            cia"할아버님 안경이 꽤 오래 되셨잖아요!"
            cia"그래서 제가 새걸로 샀어요."
            grandpa"정말 고맙구나, 시아……"
            cia"안경 도수도 맞춰져 있으니까 바로 껴 보실수 있을거예요."
            grandpa"그럼 당장 껴 봐야겠네"
            "할아버지는 자신이 끼고 있던 안경을 벗고 새로운걸 착용했다."
            grandpa"어때?"
            seb"정말 잘 어울려요!"
            seb"그리고 할아버님, 이건 제가 드리는 선물입니다."
            seb"시아것보단 형편이 없을지도 모르겠지만……"
            "세바스찬은 테이블 밑에서 케이크가 든 상자를 꺼냈다."
            seb"생신 축하드립니다."
            grandpa"생일 케이크라……"
            seb"할아버님의 연새가 올해 들어서 81세 시죠?"
            grandpa"벌써 그렇게 됐구나……{cps=2} {/cps}허허……"
            "세바스찬은 긴 초 8개랑 짧은 초 1개를 케이크 위에 꽂았다."
            "그리고 라이터로 각 촛불에 불을 붙히면서 할아버지 한테 말했다."
            seb"생일 하면 역시 촛불을 끄면서 비는 소원이죠"
            grandpa"이거 이거……"
            grandpa"이 나이가 되서 이런걸 하게 될줄이야"
            seb"무언가를 축하하는데 나이가 무슨 상관이겠습니까?"
            grandpa"하긴"
            grandpa"그럼……"
            "할아버지는 숨을 크게 들이 쉬더니 케이크 위에 있던 촛불을 향해서 바람을 불었다."
            "두번 정도 숨을 불어 넣었더니 촛불이 전부 꺼졌다."
            play sound "se/clapping.mp3"
            "우리는 할아버지의 생신을 축하하며 박수를 쳤다."
            show stephan shock2
            stephan_think"이제 내 차롄가……"
            "처음엔 나를 선물로 주는 게 정말 완벽한 선물이었다고 생각했다."
            "근데 막상 주려고 하니까 너무 쪽팔렸다."
            stephan_think"그,{cps=2} {/cps}근데 이거 어떻게 줘야 하는거지?!"
            show stephan shock2 at left
            stephan"이,{cps=2} {/cps}이제 제가 선물을 줘야 할 차례네요……!"
            show stephan think at left
            stephan"음……"
            stephan"그……"
            stephan"혹시 할아버지의 30번째 생일 기억 하세요?"
            grandpa"30번째?"
            stephan"제가 드릴 생일 선물은……"
            hide stephan think
            show stephan think with dissolve
            stephan"에헴……"
            show stephan shock2
            play sound "se/think.mp3"
            show ev ribbon_stephan
            "나는 숨겨 놨던 리본을 머리위에 달았다."
            stephan"제,{cps=2} {/cps}제가 할아버지의 선물이에요!"
            stop music
            extra"…………"
            stephan_think"막상 해보니까 완전 쪽팔려!"
            stephan_think"게다가 아무도 말을 안하니까 더 민망하잖아!!"
            stephan_think"할머니가 이런 기분이었구나!"
            grandpa"…………"
            hide stephan shock2
            hide ev ribbon_stephan
            play music "bgm/happy2.mp3"
            play sound "se/think.mp3"
            show mary with memory
            show ev ribbon_mary
            grandpa"메리……"
            play sound "se/think.mp3"
            hide mary
            hide ev ribbon_mary with memory
            show stephan shock2
            show ev ribbon_stephan
            stephan"할아버지?"
            hide ev ribbon_stephan
            show stephan shock at left
            show ev ribbon_stephan at left
            grandpa"어,{cps=2} {/cps}어?"
            stephan"뭐,{cps=2} {/cps}뭐라도 말씀좀 해주세요;;"
            stephan"이거 민망하단 말이에요……"
            grandpa"미,{cps=2} {/cps}미안하구나……"
            grandpa"그냥……{cps=2} {/cps}순간 메리가 떠올라서……"
            $ renpy.vibrate(0.5)
            grandpa"콜록{cps=2} {/cps}콜록"
            grandpa"덕분에 메리를 다시 만난 기분이었어"
            grandpa"정말 고맙구나"
            show stephan at left
            stephan"마음에 드셔서 정말 다행이에요."
            cia"…………"
            show stephan shock at left
            stephan_think"어째 시아의 눈빛이 무섭다……?"
            stephan"시,{cps=2} {/cps}시아……?"
            cia"도련님……"
            hide stephan shock
            hide ev ribbon_stephan
            show effect1
            play sound "se/shock.ogg"
            cia"{size=45}그거 정말 좋은 아이디어예요!{/size}" with lshake
            hide effect1
            show stephan shock at left
            show ev ribbon_stephan at left
            stephan_think"갑자기 무슨;;"
            cia"그런 방법이 있었구나……"
            cia"자신을 선물로 준다니!"
            cia"뭔가 느끼함과 로맨틱함이 적절하고 좋아요!"
            stephan_think"진짜 감탄을 하는거야?{cps=2} {/cps}아니면 내가 쪽팔려 하지 않도록 배려 해주려는거야……?"
            "나는 후자가 맞을거라고 생각했다."
            "그런데 세바스찬은 어디선가 작은 노트를 꺼내더니 시아가 한 말을 적기 시작했다."
            seb"{size=25}로맨틱 하단 말이지……{/size}"
            stephan_think"그거 메모 하지마;;"
            show stephan shock2 at left
            stephan"그,{cps=2} {/cps}그보다 빨리 케이크를 먹는 게……"
            grandpa"다들……"
            grandpa"내가 잠깐 부탁하고 싶은 게 있는데……"
            hide stephan shock2
            hide ev ribbon_stephan
            cia"뭐든지 말씀 하세요!"
            stop music
            grandpa"케이크를 다 먹고……{cps=2} {/cps}같이 메리를 만나러 가는 걸 도와줄수 있겠니……?"
            cia"음……"
            cia"괜찮긴 하지만……"
            cia"할아버님 생일에 그곳이면 괜찮겠어요?"
            cia"좀더 즐거운곳이……"
            grandpa"스테반이 준 생일 선물을 보니까 갑자기 떠오른게 있어서……"
            grandpa"생각해보니까 내가 한동안 메리의 묘비 관리를 하지 못했더구나"
            grandpa"……역시 힘들려나"
            play music"bgm/happy1.mp3"
            cia"아니에요!"
            cia"같이가 드리겠습니다!"
            grandpa"고맙구나"
            grandpa"……그리고 스테반"
            show stephan shock2 at left
            show ev ribbon_stephan at left
            stephan"네?"
            grandpa"좋은 생일 선물이었단다."
            grandpa"정말 고마워"
            show stephan at left
            stephan"할아버지 생일에 그렇게 고맙다는 말만 해서 어떡해요."
            show stephan smile at left
            stephan"생일은 그냥 편하게 즐기시면 되는거예요."
            grandpa"그래……"
            grandpa"내 최근 50년동안 가장 행복했던 순간이 바로 오늘인거 같구나……"
            show stephan at left
            stephan"정말요?"
            stephan"일기장을 보니까 꽤 행복하게 지내셨던거 같던데?"
            grandpa"…………"
            grandpa"글쎄다……"
            scene black with slideright
            centered"오후 2시 29분"
            play music "bgm/sad4.mp3"
            "우리는 근처에서 꽃을 사서 할머니가 계시는곳으로 갔다."
            "할머니는 저택에서 얼마 안돼는곳에 묻혀 계신다고 한다."
            "이렇게 근처에 있었으면서도 나는 이곳에 처음 와보는거 같다."
            "어쩌면 어렸을때 한번 와본적이 있었지만 내가 기억을 못하는 걸수도 있겠다……"
            "뭐가 어쨌건 모든게 새롭게 느껴졌다."
            "어떻게 보면 이게 나와 할머니의 첫 만남인 셈이다."
            scene bg ravine_day with dissolve
            play bgs"bgs/birds.mp3"
            "할아버지는 왼손을 주머니에 넣고, 다른손엔 꽃다발과 지팡이를 쥔채 저 멀리를 바라보고 있었다."
            seb"여기에 할머님이 계시는 건가요?"
            show stephan talk at left
            stephan"나도 여긴 처음 와보는거 같네……"
            grandpa"생각 해보니까 시아 빼곤 여긴 처음이겠구나……"
            hide stephan talk
            seb"시아는 여기에 와본적이 있었어요?"
            cia"네"
            cia"할아버님 저택에 막 들어왔을때 한번 이곳으로 데리고 와주신적이 있었어요."
            cia"근데 잠깐만 와본거라서……"
            scene bg ravine_grave #메리의 묘비
            grandpa"한동안 못오니까 잡초가 많이 자랐구나……"
            grandpa"난 허리 때문에 좀 힘들거 같으니까 세바스찬이랑 스테반이 잡초를 좀 제거해 줄수 있겠니?"
            show stephan at left
            $ extra_name = '세바스찬 & 스테반'
            extra"네!"
            "나와 세바스찬은 주변의 잡초를 제거 하기 위해서 쭈그려 앉았다."
            "우리에겐 낫같은 게 없어서 일일이 손으로 뜯어야 했다."
            hide stephan
            play sound "se/swing.mp3"
            $ renpy.vibrate(0.3)
            $ renpy.pause(1)
            play sound "se/swing.mp3"
            $ renpy.vibrate(0.3)
            $ renpy.pause(1)
            play sound "se/swing.mp3"
            $ renpy.vibrate(0.3)
            $ renpy.pause(1)
            show stephan at left
            stephan"휴~"
            stephan"이정도면 괜찮나요?"
            grandpa"어―{cps=2} {/cps}둘다 수고 했다."
            hide stephan
            play sound "se/search_bag.mp3"
            "할아버지는 손에 들고있던 꽃다발을 묘비 앞에다 놔뒀다."
            grandpa"메리……"
            grandpa"나 오늘 생일이야……"
            grandpa"같이 축하해줬으면 좋겠어"
            grandpa"또, 내가 오늘 무슨 선물을 받았는지 알아?"
            "할아버지는 이런식으로 혼자서 할머니와 대화를 하고 있었다."
            "우리들은 무슨 표정을 지어야 할지 몰랐다."
            "그저 눈을 아랫쪽으로 깔면서 묵념을 하듯이 할아버지 뒤에 서있기만 했다."
            stop bgs
    jump chapter4